### ISSUE TITLE
Is there a simple way to just require/import the compression / decompression parts of this library separately?

### ISSUE THREAD

**Issue by briangruber** [rotemdan/lzutf8.js#16]
Great work on this, btw!

Maybe this is a rookie mistake or misunderstanding, but is there a simple way if I just want to use the `LZUTF8.compress` portion and don't want or need to include all the decompression stuff in my project, or is the code not structured to allow that?

**Comment by rotemdan** [comment]
The code isn't organized to provide that. I've mentioned in another issue I wish to create a more minimal library that would only provide the basic `compress` / `uncompress` part.

I also hope to someday rewrite the compression and decompression code in a language like C/C++/Go (I already wrote an experimental C++ version several years ago) so it can be compiled to webassembly and run as a native executable as well, so I guess I might achieve both at the same time.

Unfortunately I don't really have time for that at the moment, though it might happen at some unknown future time. Currently I try to keep the library at minimal maintenance state.
