### ISSUE TITLE
RunningInNodeJS condition

### ISSUE THREAD

**Issue by amertak** [rotemdan/lzutf8.js#9]
Build 0.3.3 broke the condition.

0.3.2 was 
```
LZUTF8.runningInNodeJS = runningInNodeJS;
if (typeof module === "object" && typeof module.exports === "object") {
  module.exports = LZUTF8;
}
```
0.3.3

```
if (runningInNodeJS()) {
  module.exports = LZUTF8;
}
```

Now I cannot use it in webpack build and I am forced to use v0.3.2.
Hope it can be fixed.

Thanks for the great library anyway! 👍

**Comment by rotemdan** [comment]
Thanks for reporting. That was an unintended regression from refactor I've made in the most recent release. This should be fixed now in 0.3.5.

**Comment by rotemdan** [comment]
Please let me know if there are other issues you're experiencing.

**Comment by amertak** [comment]
It is now fixed and it's working great.

Thanks ;)
Closing
